"""Generate N x N test vectors for the tiling controller.

Emits operands already packed the way tile_ctrl's BRAM wants them, plus the
expected result in tile order, so the testbench does no reshaping.

    python model/gen_tiles.py               # T = 1,2,4,8 (N = 8,16,32,64)
    python model/gen_tiles.py --t 16        # N = 128 as well

Layout notes
------------
BRAM word w of row r holds elements [w*K .. w*K+K-1] of that row, element j at
bit offset j*DATA_W. Address is r*T + w. Both A and B use this layout, which is
why one read supplies a whole tile row for either of them.

Results come out of the array in tile order -- tile (ti,tj) complete, row-major
within the tile -- because streaming them that way avoids a full C buffer on
the FPGA. c_tiles.hex is in that same order so the comparison is direct.
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path

from matmul_model import Config, to_hex, wrap_signed

REPO = Path(__file__).resolve().parent.parent
K = 8
DATA_W = 16
ACC_W = 48


def pack_words(mat, n, t):
    """Row-major matrix -> list of K-element words, address order r*T + w."""
    words = []
    for r in range(n):
        for w in range(t):
            val = 0
            for j in range(K):
                e = mat[r][w * K + j] & 0xFFFF
                val |= e << (j * DATA_W)
            words.append(val)
    return words


def matmul_full(a, b, n):
    c = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            acc = 0
            for k in range(n):
                acc += a[i][k] * b[k][j]
            c[i][j] = wrap_signed(acc, ACC_W)
    return c


def tile_order(c, n, t):
    """Flatten C the way tile_ctrl emits it: tile (ti,tj), row-major inside."""
    out = []
    for ti in range(t):
        for tj in range(t):
            for r in range(K):
                for col in range(K):
                    out.append(c[ti * K + r][tj * K + col])
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--t", type=int, nargs="+", default=[1, 2, 4, 8],
                    help="tile counts per side; N = 8*T")
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--range", type=int, default=1000,
                    help="operand magnitude limit (keeps values readable)")
    args = ap.parse_args()

    rng = random.Random(args.seed)
    out_dir = REPO / "vectors_tiles"
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest = []

    for t in args.t:
        n = K * t
        a = [[rng.randint(-args.range, args.range) for _ in range(n)]
             for _ in range(n)]
        b = [[rng.randint(-args.range, args.range) for _ in range(n)]
             for _ in range(n)]
        c = matmul_full(a, b, n)

        aw = pack_words(a, n, t)
        bw = pack_words(b, n, t)
        cf = tile_order(c, n, t)

        (out_dir / f"a_t{t}.hex").write_text(
            "\n".join(to_hex(w, K * DATA_W) for w in aw) + "\n")
        (out_dir / f"b_t{t}.hex").write_text(
            "\n".join(to_hex(w, K * DATA_W) for w in bw) + "\n")
        (out_dir / f"c_t{t}.hex").write_text(
            "\n".join(to_hex(v, ACC_W) for v in cf) + "\n")

        words = n * t
        ideal = t**3 * (3 * K - 2)
        with_load = t**3 * (K + (3 * K - 2) + 1)
        manifest.append((t, n, words, len(cf), ideal, with_load))

        print(f"T={t:2d}  N={n:4d}  {words:5d} words each operand, "
              f"{len(cf):6d} results")

    hdr = ["// Generated by model/gen_tiles.py -- do not edit.",
           "`ifndef TILE_VECTORS_SVH", "`define TILE_VECTORS_SVH",
           f'`define TV_DIR "{out_dir.as_posix()}"',
           f"`define TV_NUM {len(manifest)}"]
    for i, (t, n, words, res, _, _) in enumerate(manifest):
        hdr += [f"`define TV{i}_T     {t}",
                f"`define TV{i}_WORDS {words}",
                f"`define TV{i}_RES   {res}"]
    hdr.append("`endif")
    (REPO / "tb" / "tile_vectors.svh").write_text("\n".join(hdr) + "\n")

    print("")
    print("expected cycle counts (100 MHz):")
    print(f"{'T':>3} {'N':>5} {'ideal':>10} {'with load':>11} {'us':>9}")
    for t, n, _, _, ideal, with_load in manifest:
        print(f"{t:3d} {n:5d} {ideal:10d} {with_load:11d} {with_load/100.0:9.2f}")


if __name__ == "__main__":
    main()
