"""Generate test vectors for the systolic array testbench.

Writes flat $readmemh files plus a SystemVerilog parameter header, so the
testbench never has to hardcode a case count or matrix size:

    vectors/a.hex        all A matrices, row-major, one value per line
    vectors/b.hex        all B matrices, row-major
    vectors/c_exp.hex    expected results, row-major
    vectors/names.txt    human-readable case names, for failure messages
    vectors/params.svh   `define K / DATA_W / ACC_W / NUM_CASES

Usage:
    python model/gen_vectors.py                    # defaults: K=8, 1000 random
    python model/gen_vectors.py --k 4 --random 200
    python model/gen_vectors.py --seed 42 --out vectors_k2 --k 2
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path

from matmul_model import (
    Config,
    constant,
    identity,
    matmul,
    random_matrix,
    to_hex,
)

REPO_ROOT = Path(__file__).resolve().parent.parent


def resolve_out(path: Path) -> Path:
    """Anchor relative output paths to the repo root, not the caller's cwd.

    Without this, `python model/gen_vectors.py` and `cd model && python
    gen_vectors.py` would write to different places and emit a VEC_DIR the
    testbench cannot find.
    """
    return path if path.is_absolute() else REPO_ROOT / path


def directed_cases(cfg: Config, rng: random.Random):
    """Corner cases that random stimulus is unlikely to hit.

    Ordered roughly by how early they should fail if the RTL is broken: a
    zeros case failing means reset is wrong, identity failing means the skew
    is misaligned, max-magnitude failing means the accumulator is too narrow.
    """
    zeros = constant(cfg, 0)
    ones = constant(cfg, 1)
    ident = identity(cfg)

    single = constant(cfg, 0)
    single[0][0] = 1

    last = constant(cfg, 0)
    last[cfg.k - 1][cfg.k - 1] = 1

    counting = [[i * cfg.k + j + 1 for j in range(cfg.k)] for i in range(cfg.k)]
    alt = [[(1 if (i + j) % 2 == 0 else -1) for j in range(cfg.k)]
           for i in range(cfg.k)]

    hi = constant(cfg, cfg.data_max)
    lo = constant(cfg, cfg.data_min)

    cases = [
        ("zeros", zeros, zeros),
        ("identity_x_identity", ident, ident),
        ("identity_x_random", ident, random_matrix(cfg, rng)),
        ("random_x_identity", random_matrix(cfg, rng), ident),
        ("ones_x_ones", ones, ones),
        ("single_element_first", single, ident),
        ("single_element_last", last, ident),
        ("counting_x_identity", counting, ident),
        ("counting_x_counting", counting, counting),
        ("alternating_signs", alt, alt),
        ("max_pos_x_max_pos", hi, hi),
        ("min_neg_x_min_neg", lo, lo),
        ("max_pos_x_min_neg", hi, lo),
        ("min_neg_x_identity", lo, ident),
        ("small_magnitude", random_matrix(cfg, rng, -4, 4),
         random_matrix(cfg, rng, -4, 4)),
        ("sparse", random_matrix(cfg, rng, -1, 1),
         random_matrix(cfg, rng, -1, 1)),
    ]
    return cases


def build(cfg: Config, num_random: int, seed: int):
    rng = random.Random(seed)
    cases = directed_cases(cfg, rng)
    for n in range(num_random):
        cases.append((f"random_{n:04d}", random_matrix(cfg, rng),
                      random_matrix(cfg, rng)))
    return cases


def write_vectors(cases, cfg: Config, out_dir: Path, seed: int) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    a_lines, b_lines, c_lines, names = [], [], [], []

    for name, a, b in cases:
        c = matmul(a, b, cfg)
        names.append(name)
        for i in range(cfg.k):
            for j in range(cfg.k):
                a_lines.append(to_hex(a[i][j], cfg.data_w))
                b_lines.append(to_hex(b[i][j], cfg.data_w))
                c_lines.append(to_hex(c[i][j], cfg.acc_w))

    (out_dir / "a.hex").write_text("\n".join(a_lines) + "\n")
    (out_dir / "b.hex").write_text("\n".join(b_lines) + "\n")
    (out_dir / "c_exp.hex").write_text("\n".join(c_lines) + "\n")
    (out_dir / "names.txt").write_text("\n".join(names) + "\n")

    # Absolute paths. Vivado's xsim runs from deep inside <proj>.sim/sim_1/,
    # so a repo-relative $readmemh path silently finds nothing there. Absolute
    # paths work identically under iverilog, xsim, and Questa. The header is a
    # generated file, so machine-specific paths in it are fine -- regenerate
    # after cloning.
    vec_dir = out_dir.resolve().as_posix()

    header = f"""// Generated by model/gen_vectors.py -- do not edit.
// seed={seed}
// Paths are absolute so they resolve from any simulator's run directory.
// Regenerate on a new machine: python model/gen_vectors.py
`ifndef VECTOR_PARAMS_SVH
`define VECTOR_PARAMS_SVH
`define VEC_K         {cfg.k}
`define VEC_DATA_W    {cfg.data_w}
`define VEC_ACC_W     {cfg.acc_w}
`define VEC_NUM_CASES {len(cases)}
`define VEC_DIR       "{vec_dir}"
`define VEC_A_HEX     "{vec_dir}/a.hex"
`define VEC_B_HEX     "{vec_dir}/b.hex"
`define VEC_C_HEX     "{vec_dir}/c_exp.hex"
`endif
"""
    (out_dir / "params.svh").write_text(header)

    # A second copy next to the testbench. Both iverilog and Vivado resolve
    # includes relative to the including file, so an include with no directory
    # component is the one form that works everywhere without configuring an
    # include path in the tool.
    tb_dir = REPO_ROOT / "tb"
    if tb_dir.is_dir():
        (tb_dir / "vector_params.svh").write_text(header)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--k", type=int, default=8, help="array dimension (default 8)")
    ap.add_argument("--data-w", type=int, default=16,
                    help="operand width in bits (default 16)")
    ap.add_argument("--random", type=int, default=1000, dest="num_random",
                    help="number of random cases (default 1000)")
    ap.add_argument("--seed", type=int, default=0xC0FFEE,
                    help="RNG seed, for reproducibility (default 0xC0FFEE)")
    ap.add_argument("--out", type=Path, default=Path("vectors"),
                    help="output directory (default vectors/)")
    args = ap.parse_args()

    cfg = Config(data_w=args.data_w, k=args.k)
    out_dir = resolve_out(args.out)
    cases = build(cfg, args.num_random, args.seed)
    write_vectors(cases, cfg, out_dir, args.seed)

    directed = len(cases) - args.num_random
    print(cfg.describe())
    print(f"wrote {len(cases)} cases to {out_dir}/ "
          f"({directed} directed + {args.num_random} random, seed 0x{args.seed:X})")
    print(f"  a.hex / b.hex     {len(cases) * cfg.k * cfg.k} values, "
          f"{(cfg.data_w + 3) // 4} hex digits each")
    print(f"  c_exp.hex         {len(cases) * cfg.k * cfg.k} values, "
          f"{(cfg.acc_w + 3) // 4} hex digits each")


if __name__ == "__main__":
    main()
