// Generated by model/gen_vectors.py -- do not edit.
// seed=12648430
// VEC_DIR is relative to the repo root; run simulation from there.
`ifndef VECTOR_PARAMS_SVH
`define VECTOR_PARAMS_SVH
`define VEC_K         8
`define VEC_DATA_W    16
`define VEC_ACC_W     35
`define VEC_NUM_CASES 1016
`define VEC_DIR       "vectors"
`define VEC_A_HEX     "vectors/a.hex"
`define VEC_B_HEX     "vectors/b.hex"
`define VEC_C_HEX     "vectors/c_exp.hex"
`endif
