// Generated by model/gen_tiles.py -- do not edit.
`ifndef TILE_VECTORS_SVH
`define TILE_VECTORS_SVH
`define TV_DIR "D:/fpga_projs/ai-mac-accelerator/vectors_tiles"
`define TV_NUM 4
`define TV0_T     1
`define TV0_WORDS 8
`define TV0_RES   64
`define TV1_T     2
`define TV1_WORDS 32
`define TV1_RES   256
`define TV2_T     4
`define TV2_WORDS 128
`define TV2_RES   1024
`define TV3_T     8
`define TV3_WORDS 512
`define TV3_RES   4096
`endif
