// Generated by model/gen_vectors.py -- do not edit.
// seed=12648430
// Paths are absolute so they resolve from any simulator's run directory.
// Regenerate on a new machine: python model/gen_vectors.py
`ifndef VECTOR_PARAMS_SVH
`define VECTOR_PARAMS_SVH
`define VEC_K         8
`define VEC_DATA_W    16
`define VEC_ACC_W     35
`define VEC_NUM_CASES 1016
`define VEC_DIR       "D:/fpga_projs/ai-mac-accelerator/vectors"
`define VEC_A_HEX     "D:/fpga_projs/ai-mac-accelerator/vectors/a.hex"
`define VEC_B_HEX     "D:/fpga_projs/ai-mac-accelerator/vectors/b.hex"
`define VEC_C_HEX     "D:/fpga_projs/ai-mac-accelerator/vectors/c_exp.hex"
`endif
